version = 2
final_space = true

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'os'
    style = 'diamond'
    powerline_symbol = ''
    leading_diamond = ''
    template = '{{.Icon}} '
    background = 'p:blue'
    foreground = 'p:wight'

  [[blocks.segments]]
    type = 'session'
    style = 'diamond'
    powerline_symbol = ''
    template = '{{ .UserName }}@{{ .HostName }}'
    background = 'p:blue'
    foreground = 'p:text'

  [[blocks.segments]]
    type = 'path'
    style = 'powerline'
    powerline_symbol = ''
    template = ' {{ .Path }}'
    background = 'p:pink'
    foreground = 'p:text'

    [blocks.segments.properties]
      folder_icon = '....'
      home_icon = '~'
      style = 'agnoster_short'

  [[blocks.segments]]
    type = 'git'
    style = 'powerline'
    powerline_symbol = ''
    template = ' {{ .HEAD }}'
    background = 'p:lavender'
    foreground = 'p:text'

    [blocks.segments.properties]
      branch_icon = ' '
      cherry_pick_icon = ' '
      commit_icon = ' '
      fetch_status = false
      fetch_upstream_icon = false
      merge_icon = ' '
      no_commits_icon = ' '
      rebase_icon = ' '
      revert_icon = ' '
      tag_icon = ' '

[[blocks]]
    type = 'prompt'
    alignment = 'right'
    overflow = 'hidden'

    [[blocks.segments]]
        type = 'executiontime'
        style = 'plain'
        foreground = 'yellow'
        background = 'transparent'
        template = '{{ div .Ms 1000 }}s'

        [blocks.segments.properties]
            threshold = 5000

[palette]
  blue = '#8AADF4'
  lavender = '#B7BDF8'
  os = '#ACB0BE'
  pink = '#F5BDE6'
  text = '#494D64'
  wight = '#FFFFFF'
