version = 2
final_space = true

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'os'
    style = 'diamond'
    powerline_symbol = ''
    leading_diamond = ''
    template = '> '
    background = 'p:red'
    foreground = 'p:base'

  [[blocks.segments]]
    type = 'session'
    style = 'diamond'
    powerline_symbol = ''
    template = '<b>{{ .UserName }}@{{ .HostName }}</b>'
    background = 'p:red'
    foreground = 'p:base'

  [[blocks.segments]]
    type = 'path'
    style = 'powerline'
    powerline_symbol = ''
    template = ' {{ .Path }}'
    background = 'p:pink'
    foreground = 'p:base'

    [blocks.segments.properties]
      folder_icon = '....'
      home_icon = '~'
      style = 'agnoster_short'

  [[blocks.segments]]
    type = 'git'
    style = 'powerline'
    powerline_symbol = ''
    template = ' {{ .HEAD }}'
    background = 'p:lavender'
    foreground = 'p:base'

    [blocks.segments.properties]
      branch_icon = ' '
      cherry_pick_icon = ' '
      commit_icon = ' '
      fetch_status = false
      fetch_upstream_icon = false
      merge_icon = ' '
      no_commits_icon = ' '
      rebase_icon = ' '
      revert_icon = ' '
      tag_icon = ' '

    
[[blocks]]
    type = 'prompt'
    alignment = 'right'
    overflow = 'hidden'

    [[blocks.segments]]
        type = "executiontime"
        style = "powerline"
        powerline_symbol = ""
        foreground = "p:yellow"
        background = "transparent"
        template = "{{ .FormattedMs }}"
        
        [block.properties]
            threshold = 500
            style = "austin"
            always_enabled = true

[[blocks]]
    type = 'prompt'
    alignment = 'left'
    newline = true

    [[blocks.segments]]
        type = 'path'
        style = 'plain'
        background = "transparent"
        foreground = 'p:red'
        template = "<p:red>└</>"


[palette]
  rosewater = '#f5e0dc'
  flamingo = '#f2cdcd'
  pink = '#f5c2e7'
  mauve = '#cba6f7'
  red = '#f38ba8'
  maroon = '#eba0ac'
  peach = '#fab387'
  yellow = '#f9e2af'
  green = '#a6e3a1'
  teal = '#94e2d5'
  sky = '#89dceb'
  sapphire = '#74c7ec'
  blue = '#89b4fa'
  lavender = '#b4befe'
  text = '#cdd6f4'
  subtext1 = '#bac2de'
  subtext0 = '#a6adc8'
  overlay2 = '#9399b2'
  overlay1 = '#7f849c'
  overlay0 = '#6c7086'
  surface2 = '#585b70'
  surface1 = '#45475a'
  surface0 = '#313244'
  base = '#1e1e2e'
  mantle = '#181825'
  crust = '#11111b'
  
 
