version = 3
final_space = true

[palette]
  base = '#1e1e2e'
  blue = '#89b4fa'
  crust = '#11111b'
  flamingo = '#f2cdcd'
  green = '#a6e3a1'
  lavender = '#b4befe'
  mantle = '#181825'
  maroon = '#eba0ac'
  mauve = '#cba6f7'
  overlay0 = '#6c7086'
  overlay1 = '#7f849c'
  overlay2 = '#9399b2'
  peach = '#fab387'
  pink = '#f5c2e7'
  red = '#f38ba8'
  rosewater = '#f5e0dc'
  sapphire = '#74c7ec'
  sky = '#89dceb'
  subtext0 = '#a6adc8'
  subtext1 = '#bac2de'
  surface0 = '#313244'
  surface1 = '#45475a'
  surface2 = '#585b70'
  teal = '#94e2d5'
  text = '#cdd6f4'
  yellow = '#f9e2af'

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    style = 'diamond'
    leading_diamond = ''
    template = '{{.Icon}} '
    foreground = 'p:base'
    powerline_symbol = ''
    background = 'p:red'
    type = 'os'

  [[blocks.segments]]
    style = 'diamond'
    template = '<b>{{ .UserName }}@{{ .HostName }}</b>'
    foreground = 'p:base'
    powerline_symbol = ''
    background = 'p:red'
    type = 'session'

  [[blocks.segments]]
    style = 'powerline'
    template = ' {{ .Path }}'
    foreground = 'p:base'
    powerline_symbol = ''
    background = 'p:pink'
    type = 'path'

    [blocks.segments.properties]
      folder_icon = '....'
      home_icon = '~'
      style = 'agnoster_short'

  [[blocks.segments]]
    style = 'powerline'
    template = ' {{ .HEAD }}'
    foreground = 'p:base'
    powerline_symbol = ''
    background = 'p:lavender'
    type = 'git'

    [blocks.segments.properties]
      branch_icon = ' '
      cherry_pick_icon = ' '
      commit_icon = ' '
      fetch_status = false
      fetch_upstream_icon = false
      merge_icon = ' '
      no_commits_icon = ' '
      rebase_icon = ' '
      revert_icon = ' '
      tag_icon = ' '

[[blocks]]
  type = 'prompt'
  alignment = 'right'
  overflow = 'hidden'

  [[blocks.segments]]
    style = 'powerline'
    template = '{{ .FormattedMs }}'
    foreground = 'p:yellow'
    powerline_symbol = ''
    background = 'transparent'
    type = 'executiontime'

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    style = 'plain'
    template = '<p:red>└</>'
    foreground = 'p:red'
    background = 'transparent'
    type = 'path'
